// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifdvafklhnjzdwboerxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmZHZhZmtsaG5qemR3Ym9lcnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDE2NDAsImV4cCI6MjA1OTE3NzY0MH0.z-Ao90-jrM8srf4QuSGFJnvEbpS3DffsrLCk8iYCjS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);