// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrmjvscuunyblxkkagxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ybWp2c2N1dW55Ymx4a2thZ3h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MTEyNDAsImV4cCI6MjA1NTQ4NzI0MH0.RSgDCOVn7t76khUY3p5_gVBS0jHrxmS3Ak2ONPZUgyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);